name: Garca

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Rust
      uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
    - name: Build and run Garca code
      run: cargo run --release
    - name: Commit generated files
      run: |
        git config user.name ${{ github.repository_owner }}
        git config user.email "paulo.granthon@fatec.sp.gov.br"
        git add .
        git commit -m "Update Cellular Automata state"
        git push
